name: build-and-test

on: [push]

jobs:
  
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Verify formatting
        run: dotnet format . --verify-no-changes --severity error -v m
        continue-on-error: false
        
      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: ./
  
  build:
    runs-on: ubuntu-latest
    needs: [precheck]
    
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: create artifact
        uses: actions/upload-artifact@v4
        with: 
          name: build-output
          path: ./src/**/bin/Release/net9.0/**
          
#  tests:
#    runs-on: ubuntu-latest
#    needs: [build]
#    
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: build-output
#
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '9.0.x'
#
#      - name: Run tests
#        run: dotnet test --no-restore --verbosity normal