name: build-and-test

on: [push]

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dotnet-analyzers
        run: dotnet tool install --global dotnet-analyzers

      - name: Run static code analysis
        run: dotnet-analyzers analyze . --severity error

      - name: Verify formatting
        run: dotnet format . --verify-no-changes --severity error -v m
        continue-on-error: false
        
      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: ./
          
  tests:
    runs-on: ubuntu-latest
    needs: [ precheck ]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
  
  build:
    runs-on: ubuntu-latest
    needs: [precheck, tests]
    
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code
          
      - name: Build
        run: dotnet build --configuration Release

      - name: create artifact
        uses: actions/upload-artifact@v4
        with: 
          name: build-output
          path: ./src/**/bin/Release/net9.0/**