name: build-and-test

on: [push]

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify formatting
        run: dotnet format . --verify-no-changes --severity error -v m

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: ./

  build:
    runs-on: ubuntu-latest
    needs: precheck
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./src/**/bin/Release/net9.0/**

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

  create-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./src/**/bin/Release/net9.0/**